/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author daniel
 */
public class Ejecucion extends javax.swing.JFrame {

    /**
     * Creates new form Ejecucion
     */
    public Ejecucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relleno1 = new javax.swing.JPanel();
        relleno2 = new javax.swing.JPanel();
        relleno3 = new javax.swing.JPanel();
        relleno4 = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        contenedorCronometro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        contenedorInformacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaAlgoritmo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relleno1.setBackground(new java.awt.Color(255, 255, 255));
        relleno1.setPreferredSize(new java.awt.Dimension(925, 35));

        javax.swing.GroupLayout relleno1Layout = new javax.swing.GroupLayout(relleno1);
        relleno1.setLayout(relleno1Layout);
        relleno1Layout.setHorizontalGroup(
            relleno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        relleno1Layout.setVerticalGroup(
            relleno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(relleno1, java.awt.BorderLayout.PAGE_START);

        relleno2.setBackground(new java.awt.Color(255, 255, 255));
        relleno2.setPreferredSize(new java.awt.Dimension(35, 545));

        javax.swing.GroupLayout relleno2Layout = new javax.swing.GroupLayout(relleno2);
        relleno2.setLayout(relleno2Layout);
        relleno2Layout.setHorizontalGroup(
            relleno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        relleno2Layout.setVerticalGroup(
            relleno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        getContentPane().add(relleno2, java.awt.BorderLayout.LINE_END);

        relleno3.setBackground(new java.awt.Color(255, 255, 255));
        relleno3.setPreferredSize(new java.awt.Dimension(925, 35));

        javax.swing.GroupLayout relleno3Layout = new javax.swing.GroupLayout(relleno3);
        relleno3.setLayout(relleno3Layout);
        relleno3Layout.setHorizontalGroup(
            relleno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        relleno3Layout.setVerticalGroup(
            relleno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(relleno3, java.awt.BorderLayout.PAGE_END);

        relleno4.setBackground(new java.awt.Color(255, 255, 255));
        relleno4.setPreferredSize(new java.awt.Dimension(35, 545));

        javax.swing.GroupLayout relleno4Layout = new javax.swing.GroupLayout(relleno4);
        relleno4.setLayout(relleno4Layout);
        relleno4Layout.setHorizontalGroup(
            relleno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        relleno4Layout.setVerticalGroup(
            relleno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        getContentPane().add(relleno4, java.awt.BorderLayout.LINE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setLayout(new java.awt.BorderLayout(0, 20));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setPreferredSize(new java.awt.Dimension(775, 150));
        panelSuperior.setLayout(new java.awt.BorderLayout(10, 0));

        contenedorCronometro.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCronometro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contenedorCronometro.setPreferredSize(new java.awt.Dimension(250, 200));

        jLabel9.setFont(new java.awt.Font("Work Sans", 1, 18)); // NOI18N
        jLabel9.setText("Tiempo:");

        jLabel10.setFont(new java.awt.Font("Work Sans", 1, 18)); // NOI18N
        jLabel10.setText("Pasos:");

        jLabel11.setText("jLabel4");

        jLabel12.setText("jLabel4");

        javax.swing.GroupLayout contenedorCronometroLayout = new javax.swing.GroupLayout(contenedorCronometro);
        contenedorCronometro.setLayout(contenedorCronometroLayout);
        contenedorCronometroLayout.setHorizontalGroup(
            contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorCronometroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        contenedorCronometroLayout.setVerticalGroup(
            contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorCronometroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(contenedorCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelSuperior.add(contenedorCronometro, java.awt.BorderLayout.LINE_END);

        contenedorInformacion.setBackground(new java.awt.Color(255, 255, 255));
        contenedorInformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Work Sans", 1, 18)); // NOI18N
        jLabel1.setText("Algoritmo:");

        etiquetaAlgoritmo.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Work Sans", 1, 18)); // NOI18N
        jLabel5.setText("Tipo:");

        jLabel6.setFont(new java.awt.Font("Work Sans", 1, 18)); // NOI18N
        jLabel6.setText("Velocidad:");

        jLabel7.setText("jLabel4");

        jLabel8.setText("jLabel4");

        javax.swing.GroupLayout contenedorInformacionLayout = new javax.swing.GroupLayout(contenedorInformacion);
        contenedorInformacion.setLayout(contenedorInformacionLayout);
        contenedorInformacionLayout.setHorizontalGroup(
            contenedorInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInformacionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(etiquetaAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        contenedorInformacionLayout.setVerticalGroup(
            contenedorInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInformacionLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(contenedorInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaAlgoritmo)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(72, 72, 72))
        );

        panelSuperior.add(contenedorInformacion, java.awt.BorderLayout.CENTER);

        panelCentral.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        panelCentral.add(panelInferior, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorCronometro;
    private javax.swing.JPanel contenedorInformacion;
    private javax.swing.JLabel etiquetaAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel relleno1;
    private javax.swing.JPanel relleno2;
    private javax.swing.JPanel relleno3;
    private javax.swing.JPanel relleno4;
    // End of variables declaration//GEN-END:variables
}
