/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cronometro;
import Modelo.Datos;
import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author daniel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    //Lista de opciones para los ComboBox
    
    
    //Titulos para la gráfica
    public static String [] titulos;

    //Titulos de los ejes principales
    public static String tituloGrafica;
    private static String rutaArchivo;
    
    //Componentes de JFreeChart
     DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
     ChartPanel panelDatos;
     JFreeChart chart;
     
    //Lectores de archivos
    JFileChooser fileChooser;
    File fichero;
    
    public Inicio() {
        initComponents();
        this.setTitle("G-SORT");
        setLocationRelativeTo(null);
    }
    
    private void crearGrafico(){
                for(Datos dato: Datos.arregloDatos){
                    if(dato != null){
                        dataSet.addValue(dato.getDatoNumerico(), dato.getDatoTexto(),dato.getDatoTexto());
                    }
                }
                chart = ChartFactory.createBarChart(tituloGrafica, titulos[0], titulos[1], dataSet, PlotOrientation.VERTICAL, true,true,false);
               
                panelDatos = new ChartPanel(chart);
                panelDatos.setMouseWheelEnabled(true);
                contenedorGrafica.add(panelDatos, BorderLayout.CENTER);
                pack();
                repaint();
    }
    
    private void reiniciarGrafica(){
        new Datos().reiniciarArreglo();
        dataSet.clear();
        repaint();
        pack();
    }
    
    //Efecto para los botones
    private void efectoHoverEntrada(JButton boton){
        boton.setForeground(new Color(47, 113, 173));
        boton.setBackground(Color.white);
        boton.setBorderPainted(true);
        boton.setBorder(new LineBorder(new Color(47, 113, 173), 3, true));
    }
    
    private void efectoHoverSalida(JButton boton){
                boton.setForeground(Color.white);
                boton.setBackground(new Color(47, 113, 173));
                boton.setBorder(new LineBorder(new Color(47, 113, 173), 3, true));
    }
    
    private void efectoPresionar(JButton boton){
        boton.setBackground(new Color(232, 245, 255));
        boton.setForeground(new java.awt.Color(47,113,173));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorCentral = new javax.swing.JPanel();
        ContenedorSuperior = new javax.swing.JPanel();
        relleno1Sup = new javax.swing.JPanel();
        relleno2Sup = new javax.swing.JPanel();
        relleno3Sup = new javax.swing.JPanel();
        relleno4Sup = new javax.swing.JPanel();
        contenedorCentralSuperior = new javax.swing.JPanel();
        contenedorSuperiorBotones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonCargar = new javax.swing.JButton();
        contenedorSuperiorCajasTexto = new javax.swing.JPanel();
        etiquetaRuta = new javax.swing.JLabel();
        cajaTituloGrafica = new javax.swing.JTextField();
        etiquetaTituloGrafica = new javax.swing.JLabel();
        cajaRutaArchivos = new javax.swing.JTextField();
        ContenedorInferior = new javax.swing.JPanel();
        relleno1Inf = new javax.swing.JPanel();
        relleno2Inf = new javax.swing.JPanel();
        relleno3Inf = new javax.swing.JPanel();
        relleno4Inf = new javax.swing.JPanel();
        contenedorCentralInferior = new javax.swing.JPanel();
        contenedorOpciones = new javax.swing.JPanel();
        etiquetaVelocidad = new javax.swing.JLabel();
        listaVelocidad = new javax.swing.JComboBox<>();
        listaAlgoritmos = new javax.swing.JComboBox<>();
        listaTipo = new javax.swing.JComboBox<>();
        botonEjecutar = new javax.swing.JButton();
        etiquetaAlgoritmos = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        contenedorGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorCentral.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCentral.setLayout(new java.awt.BorderLayout());

        ContenedorSuperior.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorSuperior.setPreferredSize(new java.awt.Dimension(786, 250));
        ContenedorSuperior.setLayout(new java.awt.BorderLayout());

        relleno1Sup.setBackground(new java.awt.Color(255, 255, 255));
        relleno1Sup.setPreferredSize(new java.awt.Dimension(15, 98));

        javax.swing.GroupLayout relleno1SupLayout = new javax.swing.GroupLayout(relleno1Sup);
        relleno1Sup.setLayout(relleno1SupLayout);
        relleno1SupLayout.setHorizontalGroup(
            relleno1SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        relleno1SupLayout.setVerticalGroup(
            relleno1SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        ContenedorSuperior.add(relleno1Sup, java.awt.BorderLayout.LINE_END);

        relleno2Sup.setBackground(new java.awt.Color(255, 255, 255));
        relleno2Sup.setPreferredSize(new java.awt.Dimension(1005, 20));

        javax.swing.GroupLayout relleno2SupLayout = new javax.swing.GroupLayout(relleno2Sup);
        relleno2Sup.setLayout(relleno2SupLayout);
        relleno2SupLayout.setHorizontalGroup(
            relleno2SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        relleno2SupLayout.setVerticalGroup(
            relleno2SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        ContenedorSuperior.add(relleno2Sup, java.awt.BorderLayout.PAGE_START);

        relleno3Sup.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout relleno3SupLayout = new javax.swing.GroupLayout(relleno3Sup);
        relleno3Sup.setLayout(relleno3SupLayout);
        relleno3SupLayout.setHorizontalGroup(
            relleno3SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        relleno3SupLayout.setVerticalGroup(
            relleno3SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        ContenedorSuperior.add(relleno3Sup, java.awt.BorderLayout.LINE_START);

        relleno4Sup.setBackground(new java.awt.Color(255, 255, 255));
        relleno4Sup.setPreferredSize(new java.awt.Dimension(1005, 40));

        javax.swing.GroupLayout relleno4SupLayout = new javax.swing.GroupLayout(relleno4Sup);
        relleno4Sup.setLayout(relleno4SupLayout);
        relleno4SupLayout.setHorizontalGroup(
            relleno4SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        relleno4SupLayout.setVerticalGroup(
            relleno4SupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        ContenedorSuperior.add(relleno4Sup, java.awt.BorderLayout.PAGE_END);

        contenedorCentralSuperior.setLayout(new java.awt.BorderLayout());

        contenedorSuperiorBotones.setBackground(new java.awt.Color(255, 255, 255));
        contenedorSuperiorBotones.setPreferredSize(new java.awt.Dimension(200, 198));
        contenedorSuperiorBotones.setSize(new java.awt.Dimension(300, 200));
        contenedorSuperiorBotones.setLayout(new java.awt.GridLayout(4, 1));
        contenedorSuperiorBotones.add(jLabel1);

        botonBuscar.setBackground(new java.awt.Color(40, 113, 173));
        botonBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setBorderPainted(false);
        botonBuscar.setContentAreaFilled(false);
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.setOpaque(true);
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonBuscarMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBuscarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBuscarMouseEntered(evt);
            }
        });
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        contenedorSuperiorBotones.add(botonBuscar);
        contenedorSuperiorBotones.add(jLabel2);

        botonCargar.setBackground(new java.awt.Color(40, 113, 173));
        botonCargar.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        botonCargar.setForeground(new java.awt.Color(255, 255, 255));
        botonCargar.setText("Cargar");
        botonCargar.setBorderPainted(false);
        botonCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCargar.setOpaque(true);
        botonCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCargarMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCargarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCargarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCargarMouseEntered(evt);
            }
        });
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });
        contenedorSuperiorBotones.add(botonCargar);

        contenedorCentralSuperior.add(contenedorSuperiorBotones, java.awt.BorderLayout.LINE_END);

        contenedorSuperiorCajasTexto.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaRuta.setFont(new java.awt.Font("Work Sans", 0, 16)); // NOI18N
        etiquetaRuta.setText("Ruta de archivos");

        cajaTituloGrafica.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 113, 173)), javax.swing.BorderFactory.createEmptyBorder(5, 7, 5, 5)));

        etiquetaTituloGrafica.setFont(new java.awt.Font("Work Sans", 0, 16)); // NOI18N
        etiquetaTituloGrafica.setText("Título de gráfica");

        cajaRutaArchivos.setFont(new java.awt.Font("Work Sans", 0, 14)); // NOI18N
        cajaRutaArchivos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 113, 173)), javax.swing.BorderFactory.createEmptyBorder(5, 7, 5, 5)));

        javax.swing.GroupLayout contenedorSuperiorCajasTextoLayout = new javax.swing.GroupLayout(contenedorSuperiorCajasTexto);
        contenedorSuperiorCajasTexto.setLayout(contenedorSuperiorCajasTextoLayout);
        contenedorSuperiorCajasTextoLayout.setHorizontalGroup(
            contenedorSuperiorCajasTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorSuperiorCajasTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorSuperiorCajasTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contenedorSuperiorCajasTextoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(etiquetaTituloGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiquetaRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaRutaArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addComponent(cajaTituloGrafica))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        contenedorSuperiorCajasTextoLayout.setVerticalGroup(
            contenedorSuperiorCajasTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorSuperiorCajasTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaRuta)
                .addGap(18, 18, 18)
                .addComponent(cajaRutaArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaTituloGrafica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cajaTituloGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        contenedorCentralSuperior.add(contenedorSuperiorCajasTexto, java.awt.BorderLayout.CENTER);

        ContenedorSuperior.add(contenedorCentralSuperior, java.awt.BorderLayout.CENTER);

        contenedorCentral.add(ContenedorSuperior, java.awt.BorderLayout.PAGE_START);

        ContenedorInferior.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorInferior.setLayout(new java.awt.BorderLayout());

        relleno1Inf.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout relleno1InfLayout = new javax.swing.GroupLayout(relleno1Inf);
        relleno1Inf.setLayout(relleno1InfLayout);
        relleno1InfLayout.setHorizontalGroup(
            relleno1InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        relleno1InfLayout.setVerticalGroup(
            relleno1InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        ContenedorInferior.add(relleno1Inf, java.awt.BorderLayout.PAGE_START);

        relleno2Inf.setBackground(new java.awt.Color(255, 255, 255));
        relleno2Inf.setPreferredSize(new java.awt.Dimension(50, 378));

        javax.swing.GroupLayout relleno2InfLayout = new javax.swing.GroupLayout(relleno2Inf);
        relleno2Inf.setLayout(relleno2InfLayout);
        relleno2InfLayout.setHorizontalGroup(
            relleno2InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        relleno2InfLayout.setVerticalGroup(
            relleno2InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        ContenedorInferior.add(relleno2Inf, java.awt.BorderLayout.LINE_START);

        relleno3Inf.setBackground(new java.awt.Color(255, 255, 255));
        relleno3Inf.setPreferredSize(new java.awt.Dimension(15, 378));

        javax.swing.GroupLayout relleno3InfLayout = new javax.swing.GroupLayout(relleno3Inf);
        relleno3Inf.setLayout(relleno3InfLayout);
        relleno3InfLayout.setHorizontalGroup(
            relleno3InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        relleno3InfLayout.setVerticalGroup(
            relleno3InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        ContenedorInferior.add(relleno3Inf, java.awt.BorderLayout.LINE_END);

        relleno4Inf.setBackground(new java.awt.Color(255, 255, 255));
        relleno4Inf.setPreferredSize(new java.awt.Dimension(1084, 35));

        javax.swing.GroupLayout relleno4InfLayout = new javax.swing.GroupLayout(relleno4Inf);
        relleno4Inf.setLayout(relleno4InfLayout);
        relleno4InfLayout.setHorizontalGroup(
            relleno4InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        relleno4InfLayout.setVerticalGroup(
            relleno4InfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        ContenedorInferior.add(relleno4Inf, java.awt.BorderLayout.PAGE_END);

        contenedorCentralInferior.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCentralInferior.setLayout(new java.awt.BorderLayout(50, 0));

        contenedorOpciones.setBackground(new java.awt.Color(255, 255, 255));
        contenedorOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Work Sans", 0, 18))); // NOI18N
        contenedorOpciones.setPreferredSize(new java.awt.Dimension(300, 363));

        etiquetaVelocidad.setFont(new java.awt.Font("Work Sans", 0, 13)); // NOI18N
        etiquetaVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaVelocidad.setText("Velocidad:");

        listaVelocidad.setFont(new java.awt.Font("Work Sans", 0, 14)); // NOI18N
        listaVelocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Lenta", "Rapida" }));
        listaVelocidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        listaAlgoritmos.setBackground(new java.awt.Color(255, 255, 255));
        listaAlgoritmos.setFont(new java.awt.Font("Work Sans", 0, 14)); // NOI18N
        listaAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burbuja", "Selección", "Inserción" }));
        listaAlgoritmos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaAlgoritmos.setOpaque(true);
        listaAlgoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlgoritmosActionPerformed(evt);
            }
        });

        listaTipo.setFont(new java.awt.Font("Work Sans", 0, 14)); // NOI18N
        listaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente", " " }));
        listaTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonEjecutar.setText("Ejecutar");
        botonEjecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEjecutar.setEnabled(false);
        botonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarActionPerformed(evt);
            }
        });

        etiquetaAlgoritmos.setFont(new java.awt.Font("Work Sans", 0, 13)); // NOI18N
        etiquetaAlgoritmos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaAlgoritmos.setText("Algoritmo:");
        etiquetaAlgoritmos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        etiquetaTipo.setFont(new java.awt.Font("Work Sans", 0, 13)); // NOI18N
        etiquetaTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaTipo.setText("Tipo:");

        javax.swing.GroupLayout contenedorOpcionesLayout = new javax.swing.GroupLayout(contenedorOpciones);
        contenedorOpciones.setLayout(contenedorOpcionesLayout);
        contenedorOpcionesLayout.setHorizontalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                        .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaVelocidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaTipo, 0, 0, Short.MAX_VALUE)
                            .addComponent(listaAlgoritmos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaVelocidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(etiquetaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        contenedorOpcionesLayout.setVerticalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaAlgoritmos, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(etiquetaAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(listaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(botonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(etiquetaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );

        contenedorCentralInferior.add(contenedorOpciones, java.awt.BorderLayout.LINE_START);

        contenedorGrafica.setBackground(new java.awt.Color(255, 255, 255));
        contenedorGrafica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gráfica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Work Sans", 0, 18))); // NOI18N
        contenedorGrafica.setLayout(new java.awt.BorderLayout());
        contenedorCentralInferior.add(contenedorGrafica, java.awt.BorderLayout.CENTER);

        ContenedorInferior.add(contenedorCentralInferior, java.awt.BorderLayout.CENTER);

        contenedorCentral.add(ContenedorInferior, java.awt.BorderLayout.CENTER);

        getContentPane().add(contenedorCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarActionPerformed
        // TODO add your handling code here:
        String tipoAlgoritmo = (String) listaAlgoritmos.getSelectedItem();
        String tipoOrden = (String) listaTipo.getSelectedItem();
        String tipoVelocidad = (String) listaVelocidad.getSelectedItem();
        new Ejecucion(tipoAlgoritmo,tipoOrden, tipoVelocidad).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonEjecutarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("/Users/daniel/Desktop/USAC PRIMER SEMESTRE 2022/IPC 1/LABORATORIO/PRACTICAS/Practica_2"));
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.CSV","csv");
        
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            fichero = fileChooser.getSelectedFile();
            
            this.cajaRutaArchivos.setText(fichero.getAbsolutePath());
        }
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
        // TODO add your handling code here:

        reiniciarGrafica();
        
        String[] datos = {"", ""};
        rutaArchivo = cajaRutaArchivos.getText();
        tituloGrafica = cajaTituloGrafica.getText();

        if((rutaArchivo != null && tituloGrafica != null) && (!"".equals(rutaArchivo) && !"".equals(tituloGrafica)) ){
            botonEjecutar.setEnabled(true);
            int contador = 0;
            
            try{
                BufferedReader bf = new BufferedReader(new FileReader(rutaArchivo));
                String bfRead;
                while((bfRead = bf.readLine()) != null){ 
                    if(contador == 0){
                        titulos = bfRead.trim().split(",");
                        
                    } else{
                    datos = bfRead.split(",");

                    Datos nuevoDato = new Datos(
                            datos[0], Integer.parseInt(datos[1].trim()));
                    
                    Datos.ingresarDatos(nuevoDato);
                    }
                    contador++;
                }
                
                crearGrafico();
                
            }catch(IOException e){
                
            }
        } else{
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los campos","Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonCargarActionPerformed

    private void listaAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAlgoritmosActionPerformed

    private void botonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseEntered
        // TODO add your handling code here:
        efectoHoverEntrada(botonBuscar);
    }//GEN-LAST:event_botonBuscarMouseEntered

    private void botonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseExited
        // TODO add your handling code here:
        efectoHoverSalida(botonBuscar);
    }//GEN-LAST:event_botonBuscarMouseExited

    private void botonCargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMouseEntered
        // TODO add your handling code here:
        efectoHoverEntrada(botonCargar);
    }//GEN-LAST:event_botonCargarMouseEntered

    private void botonCargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMouseExited
        // TODO add your handling code here:
        efectoHoverSalida(botonCargar);
    }//GEN-LAST:event_botonCargarMouseExited

    private void botonBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMousePressed
        // TODO add your handling code here:   
        efectoPresionar(botonBuscar);
    }//GEN-LAST:event_botonBuscarMousePressed

    private void botonCargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMousePressed
        // TODO add your handling code here:
        efectoPresionar(botonCargar);
    }//GEN-LAST:event_botonCargarMousePressed

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        // TODO add your handling code here:
        efectoHoverSalida(botonBuscar);
    }//GEN-LAST:event_botonBuscarMouseClicked

    private void botonCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMouseClicked
        // TODO add your handling code here:
        efectoHoverSalida(botonCargar);
    }//GEN-LAST:event_botonCargarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private void setLocationRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorInferior;
    private javax.swing.JPanel ContenedorSuperior;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JTextField cajaRutaArchivos;
    private javax.swing.JTextField cajaTituloGrafica;
    private javax.swing.JPanel contenedorCentral;
    private javax.swing.JPanel contenedorCentralInferior;
    private javax.swing.JPanel contenedorCentralSuperior;
    private javax.swing.JPanel contenedorGrafica;
    private javax.swing.JPanel contenedorOpciones;
    private javax.swing.JPanel contenedorSuperiorBotones;
    private javax.swing.JPanel contenedorSuperiorCajasTexto;
    private javax.swing.JLabel etiquetaAlgoritmos;
    private javax.swing.JLabel etiquetaRuta;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JLabel etiquetaTituloGrafica;
    private javax.swing.JLabel etiquetaVelocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> listaAlgoritmos;
    private javax.swing.JComboBox<String> listaTipo;
    private javax.swing.JComboBox<String> listaVelocidad;
    private javax.swing.JPanel relleno1Inf;
    private javax.swing.JPanel relleno1Sup;
    private javax.swing.JPanel relleno2Inf;
    private javax.swing.JPanel relleno2Sup;
    private javax.swing.JPanel relleno3Inf;
    private javax.swing.JPanel relleno3Sup;
    private javax.swing.JPanel relleno4Inf;
    private javax.swing.JPanel relleno4Sup;
    // End of variables declaration//GEN-END:variables
}
